# Generated by Django 4.2.9 on 2024-02-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uidb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
