# Generated by Django 4.2.9 on 2024-02-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_specification_size_gallery_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='instock',
            new_name='in_stock',
        ),
    ]
