# Generated by Django 4.2.9 on 2024-02-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_instock_product_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Product images'},
        ),
    ]
